# This workflow builds a sdist package for wxnat, and
# uploads it to pypi.

on:
  workflow_dispatch

jobs:
  build_sdist:
    name:    Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"

      - name: Build sdist
        run:  python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: ./dist/*.tar.gz

  publish_to_pypi:
    name:    Publish wxnat to PyPi
    runs-on: ubuntu-latest
    needs:   [build_sdist]
    steps:

      - name: Download source archive
        uses: actions/download-artifact@v2
        with:
          name: sdist
          path: dist/

      - name: Publish archives to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user:     __token__
          password: ${{ secrets.PYPI_TOKEN }}
